import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { getServerLanguage } from "@/lib/language";
import Footer from "@/components/Footer";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const language = await getServerLanguage();

    return (
        <html lang="en">
            <body className={`${inter.variable} antialiased`}>
                <Nav initialLanguage={language} />
                {children}
                <Footer />
            </body>
        </html>
    );
}
